services:
  app:
    build: .
    image: weather-pws-viewer
    container_name: weather-pws-viewer
    ports:
      - "3000:3000"
    env_file: ./.env
    environment:
      NODE_ENV: production
      PORT: "3000"
    restart: unless-stopped
